#!/usr/bin/env python3
"""Regenerate the sample lesson notebooks from source.

Run from the repo root:  python tools/build_lessons.py   (or: make notebooks)

Notebooks are authored here as plain Python (via tools/nbbuild) so they diff cleanly and
are easy to review. Outputs are intentionally left empty — learners run the cells.
"""
from __future__ import annotations

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from nbbuild import code, md, write_notebook  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# --------------------------------------------------------------------------------------
# Day 01 — Dynamic Arrays
# --------------------------------------------------------------------------------------
DAY01 = [
    md("# Day 01 — Dynamic Arrays & Amortized Analysis",
       "",
       "A dynamic array feels infinite — you keep appending and it grows. But memory is",
       "fixed-size. The trick: when the block fills, allocate a **bigger** block and copy.",
       "Grow by *doubling* and appends stay cheap on average. Let's *see* it."),
    md("## `size` vs `capacity`",
       "",
       "- **size** (`len`): how many items you actually stored.",
       "- **capacity**: how many slots you've allocated. Always `>= size`.",
       "",
       "When `size == capacity`, the next append must resize."),
    code("class DemoArray:",
         "    \"\"\"A doubling array, instrumented so we can watch it grow.\"\"\"",
         "    def __init__(self):",
         "        self.cap = 1",
         "        self.n = 0",
         "        self.data = [None] * self.cap",
         "        self.copies = 0          # total element-copies done by resizes",
         "",
         "    def append(self, v):",
         "        cost = 1                 # writing the new element is 1 unit of work",
         "        if self.n == self.cap:   # full -> grow",
         "            self.cap *= 2",
         "            new = [None] * self.cap",
         "            for i in range(self.n):",
         "                new[i] = self.data[i]",
         "                self.copies += 1",
         "            cost += self.n       # ...plus the copies this append triggered",
         "            self.data = new",
         "        self.data[self.n] = v",
         "        self.n += 1",
         "        return cost"),
    code("a = DemoArray()",
         "history = []                     # (index, size, capacity, cost_of_this_append)",
         "for i in range(17):",
         "    c = a.append(i)",
         "    history.append((i, a.n, a.cap, c))",
         "",
         "print(f\"{'append#':>7} {'size':>5} {'capacity':>9} {'cost':>5}\")",
         "for idx, n, cap, cost in history:",
         "    print(f'{idx:>7} {n:>5} {cap:>9} {cost:>5}')"),
    md("## Capacity grows as a staircase of powers of two",
       "",
       "Notice capacity jumps 1 → 2 → 4 → 8 → 16 → 32, doubling only when it has to."),
    code("import matplotlib.pyplot as plt",
         "",
         "idx = [h[0] for h in history]",
         "size = [h[1] for h in history]",
         "cap = [h[2] for h in history]",
         "",
         "plt.figure(figsize=(7, 4))",
         "plt.step(idx, cap, where='post', label='capacity (allocated)')",
         "plt.plot(idx, size, marker='o', label='size (used)')",
         "plt.xlabel('append #'); plt.ylabel('slots')",
         "plt.title('Capacity doubles; size climbs by one')",
         "plt.legend(); plt.grid(alpha=0.3); plt.show()"),
    md("## Why it's *amortized O(1)*",
       "",
       "Most appends cost 1. A few (at each resize) cost a lot. But because resizes get",
       "**exponentially rarer**, the *average* cost per append stays flat and small."),
    code("costs = [h[3] for h in history]",
         "running_avg = [sum(costs[:k + 1]) / (k + 1) for k in range(len(costs))]",
         "",
         "fig, ax = plt.subplots(figsize=(7, 4))",
         "ax.bar(idx, costs, alpha=0.4, label='cost of each append')",
         "ax.plot(idx, running_avg, color='crimson', marker='o', label='running average cost')",
         "ax.set_xlabel('append #'); ax.set_ylabel('work units')",
         "ax.set_title('Spiky per-append cost, flat average → amortized O(1)')",
         "ax.legend(); ax.grid(alpha=0.3); plt.show()",
         "",
         "print('total copies for 17 appends:', a.copies)",
         "print('average cost per append:', round(running_avg[-1], 2))"),
    md("## Takeaways",
       "",
       "- Doubling makes total copy-work across *n* appends only ~*2n* → **O(1) amortized**.",
       "- Growing by a fixed `+k` instead would cost ~*n²/(2k)* → **O(n) per append**. Try it!",
       "",
       "**Now go implement it:** open `homework.py`, then run `pytest -q`. The grader's",
       "`test_amortized_constant_appends` fails loudly if you don't double."),
]


# --------------------------------------------------------------------------------------
# Day 08 — CPU Scheduling
# --------------------------------------------------------------------------------------
DAY08 = [
    md("# Day 08 — CPU Scheduling, Visualized",
       "",
       "One CPU, many ready processes. The OS must pick who runs next. Different **policies**",
       "make different trade-offs — let's render them as **Gantt charts** on one workload."),
    md("## The workload",
       "",
       "| Process | Arrival | Burst |",
       "|---|--:|--:|",
       "| P1 | 0 | 5 |",
       "| P2 | 1 | 3 |",
       "| P3 | 2 | 1 |",
       "",
       "A **process** is a running program with its own memory; the **burst** is how much CPU",
       "time it needs before it's done. (Threads share a process's memory — more on Day 11.)"),
    code("from collections import deque",
         "",
         "WORK = [('P1', 0, 5), ('P2', 1, 3), ('P3', 2, 1)]  # (pid, arrival, burst)",
         "",
         "def fcfs(work):",
         "    segs, t = [], 0",
         "    for pid, arr, burst in sorted(work, key=lambda p: (p[1], p[0])):",
         "        s = max(t, arr); segs.append((pid, s, s + burst)); t = s + burst",
         "    return segs",
         "",
         "def sjf(work):",
         "    rem, t, segs = list(work), 0, []",
         "    while rem:",
         "        ready = [p for p in rem if p[1] <= t]",
         "        if not ready:",
         "            t = min(p[1] for p in rem); continue",
         "        pid, arr, burst = min(ready, key=lambda p: (p[2], p[1], p[0]))",
         "        rem.remove((pid, arr, burst))",
         "        s = max(t, arr); segs.append((pid, s, s + burst)); t = s + burst",
         "    return segs",
         "",
         "def round_robin(work, q):",
         "    arr = sorted(work, key=lambda p: (p[1], p[0]))",
         "    rem = {p[0]: p[2] for p in work}; ready, segs, t, i = deque(), [], 0, 0",
         "    def board(upto):",
         "        nonlocal i",
         "        while i < len(arr) and arr[i][1] <= upto:",
         "            ready.append(arr[i][0]); i += 1",
         "    board(0)",
         "    while ready or i < len(arr):",
         "        if not ready:",
         "            t = arr[i][1]; board(t); continue",
         "        pid = ready.popleft(); run = min(q, rem[pid])",
         "        segs.append((pid, t, t + run)); t += run; rem[pid] -= run",
         "        board(t)",
         "        if rem[pid] > 0: ready.append(pid)",
         "    return segs",
         "",
         "for name, segs in [('FCFS', fcfs(WORK)), ('SJF', sjf(WORK)),",
         "                   ('RR q=2', round_robin(WORK, 2))]:",
         "    print(f'{name:8}', segs)"),
    md("## Gantt charts: who holds the CPU, when"),
    code("import matplotlib.pyplot as plt",
         "",
         "policies = {'FCFS': fcfs(WORK), 'SJF': sjf(WORK), 'Round-Robin (q=2)': round_robin(WORK, 2)}",
         "colors = {'P1': '#4C72B0', 'P2': '#DD8452', 'P3': '#55A868'}",
         "",
         "fig, axes = plt.subplots(len(policies), 1, figsize=(8, 5), sharex=True)",
         "for ax, (name, segs) in zip(axes, policies.items()):",
         "    for pid, s, e in segs:",
         "        ax.broken_barh([(s, e - s)], (0, 1), facecolors=colors[pid], edgecolor='white')",
         "        ax.text((s + e) / 2, 0.5, pid, va='center', ha='center', color='white', fontsize=9)",
         "    ax.set_title(name, loc='left', fontsize=10); ax.set_yticks([])",
         "axes[-1].set_xlabel('time (ticks)')",
         "plt.tight_layout(); plt.show()"),
    md("## How they compare on average waiting time",
       "",
       "**Waiting = turnaround − burst** (time spent ready but not running)."),
    code("def avg_wait(work, segs):",
         "    completion = {}",
         "    for pid, s, e in segs:",
         "        completion[pid] = max(completion.get(pid, 0), e)",
         "    waits = [completion[pid] - arr - burst for pid, arr, burst in work]",
         "    return sum(waits) / len(waits)",
         "",
         "names = list(policies)",
         "waits = [avg_wait(WORK, policies[n]) for n in names]",
         "plt.figure(figsize=(6, 3.5))",
         "plt.bar(names, waits, color=['#4C72B0', '#55A868', '#DD8452'])",
         "plt.ylabel('avg waiting time'); plt.title('Lower is snappier')",
         "for x, w in enumerate(waits): plt.text(x, w, f'{w:.2f}', ha='center', va='bottom')",
         "plt.show()"),
    md("## Takeaways",
       "",
       "- **FCFS**: simple, but a long job makes short jobs wait (convoy effect).",
       "- **SJF**: best average wait, but needs to know burst lengths and can starve long jobs.",
       "- **Round-Robin**: fair & responsive; the quantum tunes responsiveness vs. overhead.",
       "",
       "**Now go implement all three** in `homework.py` (with proper metrics) and run `pytest -q`."),
]


# --------------------------------------------------------------------------------------
# Day 22 — Tensors & Autograd
# --------------------------------------------------------------------------------------
DAY22 = [
    md("# Day 22 — Tensors & Autograd",
       "",
       "Autograd is how every neural net learns. It looks like magic; it's just calculus.",
       "Let's watch PyTorch differentiate, then train a line by gradient descent."),
    md("## Tensors that remember their history",
       "",
       "Set `requires_grad=True` and PyTorch records the operations you do, so it can replay",
       "them backwards to get gradients. For `y = x²`, calculus says `dy/dx = 2x`:"),
    code("import torch",
         "",
         "x = torch.tensor(3.0, requires_grad=True)",
         "y = x ** 2",
         "y.backward()          # compute dy/dx",
         "print('x =', x.item(), ' y = x^2 =', y.item(), ' dy/dx =', x.grad.item(), '(should be 2x = 6)')"),
    md("## Some noisy data from a line we'll pretend we don't know",
       "",
       "True relationship: `y = 3x + 2` plus noise. Can gradient descent recover 3 and 2?"),
    code("import matplotlib.pyplot as plt",
         "torch.manual_seed(0)",
         "",
         "x = torch.linspace(-1, 1, 60)",
         "y = 3.0 * x + 2.0 + 0.3 * torch.randn(60)",
         "plt.figure(figsize=(6, 4))",
         "plt.scatter(x, y, s=15, alpha=0.7)",
         "plt.title('data: y ≈ 3x + 2 + noise'); plt.xlabel('x'); plt.ylabel('y'); plt.show()"),
    md("## The training loop (the heart of all of PyTorch)",
       "",
       "**forward → loss → backward → update → zero_grad**, repeated. Watch the loss fall."),
    code("w = torch.zeros((), requires_grad=True)",
         "b = torch.zeros((), requires_grad=True)",
         "lr, losses = 0.1, []",
         "",
         "for epoch in range(200):",
         "    pred = w * x + b                 # forward",
         "    loss = ((pred - y) ** 2).mean()  # mean squared error",
         "    loss.backward()                  # autograd fills w.grad, b.grad",
         "    with torch.no_grad():            # update without recording it",
         "        w -= lr * w.grad",
         "        b -= lr * b.grad",
         "    w.grad.zero_(); b.grad.zero_()   # gradients accumulate — clear them!",
         "    losses.append(loss.item())",
         "",
         "print(f'learned w = {w.item():.3f} (true 3.0),  b = {b.item():.3f} (true 2.0)')"),
    code("fig, (axL, axR) = plt.subplots(1, 2, figsize=(11, 4))",
         "axL.plot(losses); axL.set_title('loss curve'); axL.set_xlabel('epoch')",
         "axL.set_ylabel('MSE'); axL.grid(alpha=0.3)",
         "",
         "axR.scatter(x, y, s=15, alpha=0.6, label='data')",
         "xs = torch.linspace(-1, 1, 2)",
         "axR.plot(xs, (w * xs + b).detach(), color='crimson', lw=2, label='learned line')",
         "axR.set_title('the fit'); axR.legend(); axR.grid(alpha=0.3)",
         "plt.tight_layout(); plt.show()"),
    md("## Takeaways",
       "",
       "- `requires_grad` + `.backward()` gives you exact gradients for free.",
       "- The five-line loop above is *every* PyTorch model — bigger models just have more",
       "  parameters and fancier `forward`s.",
       "- Forgetting `zero_grad()` is the classic beginner bug; the homework grader checks for it.",
       "",
       "**Now go implement** `numerical_gradient` (to prove autograd is right) and `fit_line`",
       "in `homework.py`, then run `pytest -q`."),
]


# --------------------------------------------------------------------------------------
# Day 02 — Linked Lists
# --------------------------------------------------------------------------------------
DAY02 = [
    md("# Day 02 — Linked Lists",
       "",
       "A dynamic array stores items shoulder-to-shoulder in one block, so inserting in the",
       "middle shoves everything after it over. A **linked list** threads items with pointers",
       "instead: each node points to its neighbours. Insert/delete at a known node is O(1)."),
    md("## A node is just a value plus two pointers",
       "",
       "`prev  ⟵  [ value ]  ⟶  next`. Chain them and you get a list you can walk both ways."),
    code("class Node:",
         "    def __init__(self, value):",
         "        self.value = value; self.prev = None; self.next = None",
         "",
         "def build(values):",
         "    head = None; tail = None",
         "    for v in values:",
         "        n = Node(v)",
         "        if tail: tail.next = n; n.prev = tail",
         "        else: head = n",
         "        tail = n",
         "    return head",
         "",
         "def forward(head):",
         "    out = []",
         "    while head: out.append(head.value); head = head.next",
         "    return out",
         "",
         "head = build([1, 2, 3, 4])",
         "print('forward:', forward(head))"),
    md("## Draw the chain"),
    code("import matplotlib.pyplot as plt",
         "",
         "def draw(head, title):",
         "    vals = forward(head)",
         "    fig, ax = plt.subplots(figsize=(1.6 * len(vals) + 1, 1.8))",
         "    for i, v in enumerate(vals):",
         "        ax.add_patch(plt.Rectangle((i * 2, 0), 1.2, 1, fill=True,",
         "                                   facecolor='#4C72B0', edgecolor='black'))",
         "        ax.text(i * 2 + 0.6, 0.5, str(v), ha='center', va='center', color='white')",
         "        if i < len(vals) - 1:",
         "            ax.annotate('', xy=(i * 2 + 2, 0.65), xytext=(i * 2 + 1.2, 0.65),",
         "                        arrowprops=dict(arrowstyle='->'))",
         "            ax.annotate('', xy=(i * 2 + 1.2, 0.35), xytext=(i * 2 + 2, 0.35),",
         "                        arrowprops=dict(arrowstyle='->', color='gray'))",
         "    ax.set_xlim(-0.5, 2 * len(vals)); ax.set_ylim(-0.3, 1.3)",
         "    ax.axis('off'); ax.set_title(title); plt.show()",
         "",
         "draw(head, 'blue = next,  gray = prev')"),
    md("## Insert 99 after the 2nd node: two pointers change, nothing shifts",
       "",
       "Compare that to a Python list, where `lst.insert(2, 99)` slides every later element."),
    code("def insert_after_index(head, index, value):",
         "    cur = head",
         "    for _ in range(index): cur = cur.next",
         "    n = Node(value)",
         "    n.prev = cur; n.next = cur.next",
         "    if cur.next: cur.next.prev = n",
         "    cur.next = n",
         "    return head        # only cur.next, n.prev/next, and one neighbour touched",
         "",
         "head = insert_after_index(head, 1, 99)",
         "print('after insert:', forward(head))",
         "draw(head, 'inserted 99 after index 1 — O(1) rewire')"),
    md("## Takeaways",
       "",
       "- Linked list: O(1) insert/delete at a known node, O(n) to *find* the i-th item.",
       "- Dynamic array: O(1) random access, O(n) middle insert.",
       "- *Doubly* linked (both `prev` and `next`) is what makes O(1) deletion and backward",
       "  walking possible.",
       "",
       "**Now build the real thing** in `homework.py` — the grader checks forward *and*",
       "backward traversal after every operation, so broken `prev` links get caught."),
]


# --------------------------------------------------------------------------------------
# Day 10 — Virtual Memory & Paging
# --------------------------------------------------------------------------------------
DAY10 = [
    md("# Day 10 — Virtual Memory & Page Replacement",
       "",
       "Memory is split into fixed-size **pages**; a **page table** maps virtual pages to",
       "physical frames. A miss is a **page fault** — load the page, maybe evict another.",
       "Which one to evict is the policy. Let's watch FIFO and LRU, and meet Belady's anomaly."),
    md("## 1. Address translation",
       "",
       "`vpn, offset = divmod(vaddr, page_size)`; the offset passes through, the page is remapped."),
    code("def translate(vaddr, page_size, page_table):",
         "    vpn, offset = divmod(vaddr, page_size)",
         "    if vpn not in page_table: raise KeyError(f'page fault: vpn {vpn}')",
         "    return page_table[vpn] * page_size + offset",
         "",
         "# page 1 -> frame 2, page size 256; vaddr 356 = page 1, offset 100",
         "print('vaddr 356 ->', translate(356, 256, {0: 5, 1: 2}), '(= frame 2 * 256 + 100)')"),
    md("## 2. FIFO vs LRU on the classic reference string"),
    code("from collections import OrderedDict, deque",
         "",
         "BELADY = [1, 2, 3, 4, 1, 2, 5, 1, 2, 3, 4, 5]",
         "",
         "def fifo(refs, k):",
         "    frames, order, faults = set(), deque(), 0",
         "    for p in refs:",
         "        if p not in frames:",
         "            faults += 1",
         "            if len(frames) >= k: frames.discard(order.popleft())",
         "            frames.add(p); order.append(p)",
         "    return faults",
         "",
         "def lru(refs, k):",
         "    frames, faults = OrderedDict(), 0",
         "    for p in refs:",
         "        if p in frames: frames.move_to_end(p)",
         "        else:",
         "            faults += 1",
         "            if len(frames) >= k: frames.popitem(last=False)",
         "            frames[p] = None",
         "    return faults",
         "",
         "print('FIFO 3 frames:', fifo(BELADY, 3), 'faults')",
         "print('FIFO 4 frames:', fifo(BELADY, 4), 'faults  <-- MORE frames, MORE faults!')",
         "print('LRU  3 frames:', lru(BELADY, 3), 'faults')"),
    md("## 3. Belady's anomaly, plotted",
       "",
       "For a well-behaved policy, more frames ⇒ fewer (or equal) faults. FIFO breaks that."),
    code("import matplotlib.pyplot as plt",
         "",
         "frames = list(range(1, 7))",
         "fifo_faults = [fifo(BELADY, k) for k in frames]",
         "lru_faults = [lru(BELADY, k) for k in frames]",
         "",
         "plt.figure(figsize=(7, 4))",
         "plt.plot(frames, fifo_faults, marker='o', label='FIFO')",
         "plt.plot(frames, lru_faults, marker='s', label='LRU')",
         "plt.axvspan(2.5, 4.5, color='crimson', alpha=0.08)",
         "plt.text(3.5, max(fifo_faults), 'FIFO goes UP here\\n(Belady anomaly)',",
         "         ha='center', va='top', color='crimson', fontsize=9)",
         "plt.xlabel('number of frames'); plt.ylabel('page faults')",
         "plt.title('More memory should mean fewer faults — FIFO disagrees')",
         "plt.legend(); plt.grid(alpha=0.3); plt.show()"),
    md("## Takeaways",
       "",
       "- Translation splits an address into (page, offset); only the page is remapped.",
       "- FIFO evicts by *load order* and can suffer **Belady's anomaly** — more frames, more",
       "  faults. LRU evicts by *use order* and never does (it's a 'stack algorithm').",
       "",
       "**Now implement** `translate`, `fifo`, and `lru` in `homework.py` (returning per-step",
       "history), then run `pytest -q`."),
]


# --------------------------------------------------------------------------------------
# Day 04 — Hash Maps
# --------------------------------------------------------------------------------------
DAY04 = [
    md("# Day 04 — Hash Maps, Visualized",
       "",
       "A hash function turns a key into a bucket index. Collisions are inevitable; with linear",
       "probing we just walk to the next open slot. Let's watch it, then see why we must resize."),
    md("## Keys land in buckets; collisions probe forward"),
    code("CAP = 8",
         "buckets = [None] * CAP",
         "",
         "def insert(k):",
         "    i = k % CAP; probes = 0",
         "    while buckets[i] is not None:",
         "        i = (i + 1) % CAP; probes += 1",
         "    buckets[i] = k",
         "    return i, probes",
         "",
         "for k in [5, 13, 21, 3, 11]:   # 5, 13, 21 all hash to slot 5 -> collisions",
         "    slot, p = insert(k)",
         "    print(f'insert {k:2d} -> slot {slot}   ({p} extra probes)')",
         "print('buckets:', buckets)"),
    md("## Average probe length explodes as the table fills",
       "",
       "This is *why* a hash map resizes once it's ~70% full — beyond that, lookups slow down fast."),
    code("import matplotlib.pyplot as plt, random",
         "",
         "def avg_probes(load, cap=1000):",
         "    table = [None] * cap; n = int(load * cap); total = 0",
         "    for _ in range(n):",
         "        i = random.randrange(10**9) % cap; steps = 1",
         "        while table[i] is not None:",
         "            i = (i + 1) % cap; steps += 1",
         "        table[i] = 1; total += steps",
         "    return total / max(n, 1)",
         "",
         "loads = [i / 20 for i in range(1, 20)]",
         "plt.figure(figsize=(7, 4))",
         "plt.plot(loads, [avg_probes(l) for l in loads], marker='o')",
         "plt.axvline(0.7, color='crimson', ls='--', label='resize threshold ~0.7')",
         "plt.xlabel('load factor'); plt.ylabel('avg probes per insert')",
         "plt.title('Average probe length vs. how full the table is')",
         "plt.legend(); plt.grid(alpha=0.3); plt.show()"),
    md("## Takeaways",
       "",
       "- Hash → index gives O(1) *average* lookup; collisions are handled by probing.",
       "- Deletion must leave a **tombstone**, or you break other keys' probe chains.",
       "- Keep the load factor under ~0.7 by resizing, or probe chains blow up.",
       "",
       "**Now build the real thing** in `homework.py` (with tombstones + resize) and run `pytest -q`."),
]


# --------------------------------------------------------------------------------------
# Day 05 — Binary Search Trees
# --------------------------------------------------------------------------------------
DAY05 = [
    md("# Day 05 — Binary Search Trees, Visualized",
       "",
       "Smaller left, larger right. That invariant makes search O(height) and an in-order walk",
       "come out **sorted** — unless you insert already-sorted data and the tree collapses."),
    code("class N:",
         "    def __init__(self, v): self.v = v; self.l = None; self.r = None",
         "",
         "def insert(root, v):",
         "    if root is None: return N(v)",
         "    if v < root.v: root.l = insert(root.l, v)",
         "    elif v > root.v: root.r = insert(root.r, v)",
         "    return root",
         "",
         "def in_order(root, out):",
         "    if root: in_order(root.l, out); out.append(root.v); in_order(root.r, out)",
         "",
         "root = None",
         "for v in [5, 3, 8, 1, 4, 7, 9]: root = insert(root, v)",
         "out = []; in_order(root, out); print('in-order traversal (sorted!):', out)"),
    md("## Draw it"),
    code("import matplotlib.pyplot as plt",
         "",
         "def draw(root, title):",
         "    pos = {}; counter = [0]",
         "    def assign(node, depth):",
         "        if node is None: return",
         "        assign(node.l, depth + 1)",
         "        pos[node] = (counter[0], -depth); counter[0] += 1",
         "        assign(node.r, depth + 1)",
         "    assign(root, 0)",
         "    fig, ax = plt.subplots(figsize=(7, 4))",
         "    def edges(node):",
         "        if node is None: return",
         "        for c in (node.l, node.r):",
         "            if c: ax.plot([pos[node][0], pos[c][0]], [pos[node][1], pos[c][1]], color='gray', zorder=1)",
         "        edges(node.l); edges(node.r)",
         "    edges(root)",
         "    for node, (x, y) in pos.items():",
         "        ax.scatter([x], [y], s=650, color='#4C72B0', zorder=2)",
         "        ax.text(x, y, str(node.v), ha='center', va='center', color='white', zorder=3)",
         "    ax.set_title(title); ax.axis('off'); plt.show()",
         "",
         "draw(root, 'A reasonably balanced BST')"),
    md("## The failure mode: insert already-sorted data",
       "",
       "The tree degenerates into a linked list — height n−1, and search is back to O(n)."),
    code("bad = None",
         "for v in [1, 2, 3, 4, 5]: bad = insert(bad, v)",
         "draw(bad, 'Sorted insert -> degenerate chain (this is why balanced trees exist)')"),
    md("## Takeaways",
       "",
       "- In-order traversal of a BST is sorted; search/insert/delete are O(height).",
       "- Balanced height is O(log n); a degenerate tree is O(n). Real systems use *self-balancing*",
       "  trees (red-black, B-trees) to guarantee the good case.",
       "",
       "**Now implement** insert / contains / in_order / delete in `homework.py`, then `pytest -q`."),
]


# --------------------------------------------------------------------------------------
# Day 06 — Heaps
# --------------------------------------------------------------------------------------
DAY06 = [
    md("# Day 06 — Heaps, Visualized",
       "",
       "A binary heap is a complete tree packed into an array: children of index `i` are `2i+1`",
       "and `2i+2`, and every parent ≤ its children. The min is always at index 0."),
    code("def sift_up(a, i):",
         "    while i > 0 and a[i] < a[(i - 1) // 2]:",
         "        a[i], a[(i - 1) // 2] = a[(i - 1) // 2], a[i]; i = (i - 1) // 2",
         "",
         "heap = []",
         "for v in [5, 3, 8, 1, 9, 2, 7]:",
         "    heap.append(v); sift_up(heap, len(heap) - 1)",
         "print('heap array:', heap, ' -> min at index 0:', heap[0])"),
    md("## The array *is* a tree"),
    code("import matplotlib.pyplot as plt",
         "",
         "def draw_heap(a, title):",
         "    fig, ax = plt.subplots(figsize=(7, 4))",
         "    pos = {}",
         "    import math",
         "    for i in range(len(a)):",
         "        depth = int(math.log2(i + 1)); span = 2 ** depth",
         "        offset = (i + 1) - span",
         "        x = (offset + 0.5) / span; pos[i] = (x, -depth)",
         "    for i in range(len(a)):",
         "        for c in (2 * i + 1, 2 * i + 2):",
         "            if c < len(a): ax.plot([pos[i][0], pos[c][0]], [pos[i][1], pos[c][1]], color='gray', zorder=1)",
         "    for i, (x, y) in pos.items():",
         "        ax.scatter([x], [y], s=650, color='#55A868', zorder=2)",
         "        ax.text(x, y, str(a[i]), ha='center', va='center', color='white', zorder=3)",
         "    ax.set_title(title); ax.axis('off'); plt.show()",
         "",
         "draw_heap(heap, 'Min-heap: every parent <= its children')"),
    md("## Heapsort: pop the min until empty"),
    code("import heapq",
         "data = [5, 3, 8, 1, 9, 2, 7, 4, 6, 0]",
         "h = data[:]; heapq.heapify(h)",
         "ordered = [heapq.heappop(h) for _ in range(len(h))]",
         "print('heapsorted:', ordered)",
         "assert ordered == sorted(data)"),
    md("## Takeaways",
       "",
       "- O(1) peek-min, O(log n) push/pop, O(n) to heapify — all with pure index math, no pointers.",
       "- Pop-until-empty is heapsort: O(n log n), in place.",
       "- A heap is the priority queue behind Dijkstra/A* and the SJF scheduler (Day 08).",
       "",
       "**Now implement** sift_up / sift_down / push / pop / heapify in `homework.py`."),
]


# --------------------------------------------------------------------------------------
# Day 07 — Graphs
# --------------------------------------------------------------------------------------
DAY07 = [
    md("# Day 07 — Graphs, BFS & Grid Pathfinding, Visualized",
       "",
       "BFS explores in rings of increasing distance, so on an unweighted graph it finds the",
       "shortest path. The same idea routes around walls on a grid — a toy motion planner."),
    md("## BFS distances from a start node"),
    code("from collections import deque",
         "",
         "adj = {0: [1, 2], 1: [0, 3], 2: [0, 3], 3: [1, 2, 4], 4: [3]}",
         "",
         "def bfs_dist(adj, start):",
         "    dist = {start: 0}; q = deque([start])",
         "    while q:",
         "        u = q.popleft()",
         "        for v in adj[u]:",
         "            if v not in dist: dist[v] = dist[u] + 1; q.append(v)",
         "    return dist",
         "",
         "print('distance from 0:', bfs_dist(adj, 0))"),
    md("## Shortest path on a grid ('#' = wall)"),
    code("import matplotlib.pyplot as plt",
         "import numpy as np",
         "",
         "grid = ['.....', '.###.', '.....']",
         "start, goal = (0, 0), (2, 4)",
         "",
         "def grid_path(grid, start, goal):",
         "    R, C = len(grid), len(grid[0])",
         "    ok = lambda r, c: 0 <= r < R and 0 <= c < C and grid[r][c] != '#'",
         "    q = deque([start]); parent = {start: None}",
         "    while q:",
         "        r, c = q.popleft()",
         "        if (r, c) == goal: break",
         "        for dr, dc in ((-1, 0), (1, 0), (0, -1), (0, 1)):",
         "            n = (r + dr, c + dc)",
         "            if ok(*n) and n not in parent: parent[n] = (r, c); q.append(n)",
         "    if goal not in parent: return None",
         "    path = [goal]",
         "    while parent[path[-1]] is not None: path.append(parent[path[-1]])",
         "    return path[::-1]",
         "",
         "path = grid_path(grid, start, goal)",
         "img = np.array([[0 if ch == '#' else 1 for ch in row] for row in grid], dtype=float)",
         "for (r, c) in path: img[r][c] = 0.5",
         "plt.figure(figsize=(5, 3))",
         "plt.imshow(img, cmap='Blues'); plt.title(f'shortest path: {len(path)} cells')",
         "plt.xticks([]); plt.yticks([]); plt.show()",
         "print('path:', path)"),
    md("## Takeaways",
       "",
       "- BFS (queue) = shortest path by edge count; DFS (stack/recursion) = deep exploration.",
       "- A grid is just a graph with up/down/left/right edges — the same BFS routes around walls.",
       "- Add edge weights and BFS becomes Dijkstra, with the priority queue from Day 06.",
       "",
       "**Now implement** bfs / dfs / shortest_path / grid_shortest_path in `homework.py`."),
]


# --------------------------------------------------------------------------------------
# Day 09 — Process Lifecycle
# --------------------------------------------------------------------------------------
DAY09 = [
    md("# Day 09 — The Process Lifecycle, Visualized",
       "",
       "A process moves through states as the OS admits, dispatches, preempts, blocks, and reaps",
       "it. Every `dispatch` is a context switch. Let's drive one through a realistic run."),
    code("TRANSITIONS = {",
         "    ('new', 'admit'): 'ready',",
         "    ('ready', 'dispatch'): 'running',",
         "    ('running', 'timeout'): 'ready',",
         "    ('running', 'wait'): 'waiting',",
         "    ('waiting', 'wakeup'): 'ready',",
         "    ('running', 'exit'): 'terminated',",
         "}",
         "",
         "state = 'new'; history = [state]; switches = 0",
         "events = ['admit', 'dispatch', 'timeout', 'dispatch', 'wait', 'wakeup', 'dispatch', 'exit']",
         "for e in events:",
         "    state = TRANSITIONS[(state, e)]; history.append(state)",
         "    if e == 'dispatch': switches += 1",
         "    print(f'{e:9} -> {state}')",
         "print('\\ncontext switches (CPU grants):', switches)"),
    md("## The run as a timeline of states"),
    code("import matplotlib.pyplot as plt",
         "",
         "order = ['terminated', 'waiting', 'ready', 'running', 'new']",
         "ys = [order.index(s) for s in history]",
         "plt.figure(figsize=(8, 3))",
         "plt.step(range(len(history)), ys, where='post', marker='o')",
         "plt.yticks(range(len(order)), order)",
         "plt.xlabel('event #'); plt.title('One process walking its lifecycle')",
         "plt.grid(alpha=0.3); plt.show()"),
    md("## Takeaways",
       "",
       "- A process is a state machine; the OS only allows legal transitions.",
       "- A blocked (`waiting`) process must be woken to `ready` before it can run again.",
       "- Each `dispatch` is a context switch — cheap, but not free.",
       "",
       "**Now build the machine** in `homework.py` (rejecting illegal transitions) and `pytest -q`."),
]


# --------------------------------------------------------------------------------------
# Day 11 — Threads & the GIL
# --------------------------------------------------------------------------------------
DAY11 = [
    md("# Day 11 — Threads, Processes & the GIL, Visualized",
       "",
       "CPython's Global Interpreter Lock lets only one thread run Python bytecode at a time. So",
       "for CPU-bound work, threads give **no speedup** — but processes do. Let's measure it."),
    code("import time",
         "from concurrent.futures import ThreadPoolExecutor, ProcessPoolExecutor",
         "",
         "def heavy(n):",
         "    total = 0",
         "    for i in range(n): total += i * i",
         "    return total",
         "",
         "TASKS = [5_000_000] * 4",
         "",
         "def timed(runner, label):",
         "    t = time.perf_counter(); runner(); dt = time.perf_counter() - t",
         "    print(f'{label:22} {dt:.2f}s'); return dt",
         "",
         "serial = timed(lambda: [heavy(n) for n in TASKS], 'serial')",
         "threads = timed(lambda: list(ThreadPoolExecutor(4).map(heavy, TASKS)), 'threads (GIL-bound)')"),
    md("## Processes sidestep the GIL",
       "",
       "(Runs best on Linux/macOS. Each process has its own interpreter, so they run in true parallel.)"),
    code("import matplotlib.pyplot as plt",
         "",
         "try:",
         "    procs = timed(lambda: list(ProcessPoolExecutor(4).map(heavy, TASKS)), 'processes')",
         "except Exception as e:",
         "    print('process pool unavailable here:', e); procs = serial",
         "",
         "labels = ['serial', 'threads', 'processes']",
         "times = [serial, threads, procs]",
         "plt.figure(figsize=(6, 3.5))",
         "plt.bar(labels, times, color=['#888', '#DD8452', '#55A868'])",
         "plt.ylabel('seconds (lower is better)')",
         "plt.title('CPU-bound: threads ~ serial (GIL), processes win')",
         "for i, t in enumerate(times): plt.text(i, t, f'{t:.2f}s', ha='center', va='bottom')",
         "plt.show()"),
    md("## Takeaways",
       "",
       "- Threads don't speed up CPU-bound Python (GIL) — but they're great for **I/O-bound** work.",
       "- Processes achieve real parallelism at the cost of not sharing memory (must pass messages).",
       "- Rule of thumb: I/O-bound → threads/async; CPU-bound → processes.",
       "",
       "**Now build** chunk / threaded_sum / parallel_map in `homework.py`, then `pytest -q`."),
]


# --------------------------------------------------------------------------------------
# Day 12 — Synchronization
# --------------------------------------------------------------------------------------
DAY12 = [
    md("# Day 12 — Locks: the Lost-Update Race, Visualized",
       "",
       "`x += 1` is load-add-store, not atomic. Two threads can read the same value and one",
       "increment vanishes. Watch it happen, then watch a lock fix it."),
    code("import threading",
         "",
         "def run_counter(use_lock, threads_n=8, per_thread=50_000):",
         "    value = [0]; lock = threading.Lock()",
         "    def work():",
         "        for _ in range(per_thread):",
         "            if use_lock:",
         "                with lock: value[0] += 1",
         "            else:",
         "                value[0] += 1",
         "    ts = [threading.Thread(target=work) for _ in range(threads_n)]",
         "    for t in ts: t.start()",
         "    for t in ts: t.join()",
         "    return value[0], threads_n * per_thread",
         "",
         "got, expected = run_counter(use_lock=False)",
         "print(f'NO lock:   got {got:,} of {expected:,}  (lost {expected - got:,} updates)')",
         "got, expected = run_counter(use_lock=True)",
         "print(f'WITH lock: got {got:,} of {expected:,}  (exact)')"),
    md("## Lost updates across several unlocked runs"),
    code("import matplotlib.pyplot as plt",
         "",
         "runs = [run_counter(use_lock=False) for _ in range(6)]",
         "expected = runs[0][1]",
         "losses = [expected - got for got, _ in runs]",
         "plt.figure(figsize=(6, 3.5))",
         "plt.bar(range(len(losses)), losses, color='#DD8452')",
         "plt.axhline(0, color='#55A868', lw=2, label='with a lock: always 0')",
         "plt.xlabel('unlocked run #'); plt.ylabel('updates lost to the race')",
         "plt.title('Races are nondeterministic — and always wrong'); plt.legend(); plt.show()"),
    md("## Takeaways",
       "",
       "- Unprotected read-modify-write across threads silently loses updates.",
       "- A lock makes the critical section mutually exclusive and the result exact.",
       "- For waiting on a condition (buffer full/empty), use a condition variable and a `while` loop.",
       "",
       "**Now build** SafeCounter and BoundedBuffer in `homework.py`, then `pytest -q`."),
]


# --------------------------------------------------------------------------------------
# Day 13 — Deadlock
# --------------------------------------------------------------------------------------
DAY13 = [
    md("# Day 13 — Deadlock = a Cycle in the Wait-For Graph, Visualized",
       "",
       "A holds lock 1 wants lock 2; B holds lock 2 wants lock 1. Nobody moves. Drawn as",
       "'who waits for whom', that's a cycle — the same cycle detection from Day 07."),
    code("def find_cycle(wait_for):",
         "    color = {u: 0 for u in set(wait_for) | {v for vs in wait_for.values() for v in vs}}",
         "    path = []",
         "    def dfs(u):",
         "        color[u] = 1; path.append(u)",
         "        for v in sorted(wait_for.get(u, []), key=str):",
         "            if color[v] == 1: return path[path.index(v):]",
         "            if color[v] == 0:",
         "                r = dfs(v)",
         "                if r: return r",
         "        color[u] = 2; path.pop(); return None",
         "    for u in sorted(color, key=str):",
         "        if color[u] == 0:",
         "            r = dfs(u)",
         "            if r: return r",
         "    return None",
         "",
         "print('deadlocked:', find_cycle({'A': ['B'], 'B': ['A']}))",
         "print('safe:      ', find_cycle({'A': ['B'], 'B': ['C'], 'C': []}))"),
    md("## Reproduce, then prevent, a real two-lock deadlock",
       "",
       "We use `acquire(timeout=...)` so the demo *reports* the deadlock instead of hanging forever."),
    code("import threading, time",
         "",
         "L1, L2 = threading.Lock(), threading.Lock()",
         "stuck = []",
         "def t1():",
         "    with L1:",
         "        time.sleep(0.1)",
         "        if not L2.acquire(timeout=0.5): stuck.append('T1 could not get L2')",
         "        else: L2.release()",
         "def t2():",
         "    with L2:",
         "        time.sleep(0.1)",
         "        if not L1.acquire(timeout=0.5): stuck.append('T2 could not get L1')",
         "        else: L1.release()",
         "a, b = threading.Thread(target=t1), threading.Thread(target=t2)",
         "a.start(); b.start(); a.join(); b.join()",
         "print('opposite order  ->', stuck or 'no deadlock (got lucky)')",
         "print('fix: always acquire locks in the same global order (sorted by id/name)')"),
    md("## Takeaways",
       "",
       "- Deadlock = a cycle in the wait-for graph; detect it with DFS cycle-finding.",
       "- Acquiring locks in one consistent global order removes the 'circular wait' condition,",
       "  so no cycle can ever form.",
       "",
       "**Now build** find_deadlock_cycle / has_deadlock / safe_lock_order, then `pytest -q`."),
]


# --------------------------------------------------------------------------------------
# Day 14 — IPC & Pipes
# --------------------------------------------------------------------------------------
DAY14 = [
    md("# Day 14 — Framing Messages Over a Pipe, Visualized",
       "",
       "A pipe is a raw byte stream — no message boundaries. Prefix each message with its length",
       "and the receiver can always find where one ends and the next begins."),
    code("import struct",
         "",
         "def frame(payload): return struct.pack('>I', len(payload)) + payload",
         "def parse(buf):",
         "    msgs, i = [], 0",
         "    while len(buf) - i >= 4:",
         "        (ln,) = struct.unpack('>I', buf[i:i+4])",
         "        if len(buf) - i - 4 < ln: break",
         "        msgs.append(buf[i+4:i+4+ln]); i += 4 + ln",
         "    return msgs, buf[i:]",
         "",
         "stream = frame(b'hello') + frame(b'world')",
         "print('raw bytes:', stream)",
         "print('parsed:   ', parse(stream)[0])"),
    md("## Send framed messages through a real `os.pipe()` between two threads"),
    code("import os, threading",
         "",
         "r, w = os.pipe()",
         "messages = [b'SET x 1', b'GET x', b'KEYS']",
         "",
         "def sender():",
         "    for m in messages: os.write(w, frame(m))",
         "    os.close(w)",
         "",
         "received = []",
         "def receiver():",
         "    buf = b''",
         "    while True:",
         "        chunk = os.read(r, 3)      # tiny reads: frames arrive split up",
         "        if not chunk: break",
         "        buf += chunk",
         "        msgs, buf = parse(buf)",
         "        received.extend(msgs)",
         "    os.close(r)",
         "",
         "ts = threading.Thread(target=sender), threading.Thread(target=receiver)",
         "ts[0].start(); ts[1].start(); ts[0].join(); ts[1].join()",
         "print('received:', received)"),
    md("## Takeaways",
       "",
       "- Byte streams have no message boundaries; length-prefix framing restores them.",
       "- The parser holds an incomplete frame as *leftover* until the rest of the bytes arrive.",
       "- Pipes, sockets, and files are all 'a stream of bytes behind a file descriptor'.",
       "",
       "**Now build** frame / parse_frames / KVStore / serve in `homework.py`, then `pytest -q`."),
]


# --------------------------------------------------------------------------------------
# Day 15 — Memory Model & Bump Allocator
# --------------------------------------------------------------------------------------
DAY15 = [
    md("# Day 15 — Memory Model & a Bump Allocator, Visualized",
       "",
       "A process's address space has a **stack** (grows down, automatic) and a **heap** (grows",
       "up, you manage it). A bump allocator carves the heap by advancing a cursor — fast, and",
       "allocation-free at steady state."),
    md("## A process's address space (schematically)",
       "",
       "```",
       "  high addr  |  stack   |  <- grows DOWN (locals, call frames)",
       "             |    |     |",
       "             |    v     |",
       "             |          |",
       "             |    ^     |",
       "             |    |     |",
       "             |  heap    |  <- grows UP (malloc / your allocator)",
       "  low addr   |  code    |",
       "```"),
    code("class Bump:",
         "    def __init__(self, cap): self.cap = cap; self.off = 0; self.blocks = []",
         "    def alloc(self, size, align=1):",
         "        start = ((self.off + align - 1) // align) * align",
         "        if start + size > self.cap: raise MemoryError('OOM')",
         "        self.blocks.append((self.off, start, size))  # (padding_start, block_start, size)",
         "        self.off = start + size; return start",
         "",
         "a = Bump(64)",
         "a.alloc(3)          # 3 bytes",
         "a.alloc(8, align=8) # aligned to 8 -> padding inserted",
         "a.alloc(4, align=4)",
         "print('blocks (pad_start, start, size):', a.blocks)",
         "print('used:', a.off, 'of', a.cap)"),
    md("## The arena, drawn (blue = data, red = alignment padding)"),
    code("import matplotlib.pyplot as plt",
         "",
         "fig, ax = plt.subplots(figsize=(9, 1.6))",
         "for pad_start, start, size in a.blocks:",
         "    if start > pad_start:",
         "        ax.barh(0, start - pad_start, left=pad_start, color='#DD8452')  # padding",
         "    ax.barh(0, size, left=start, color='#4C72B0', edgecolor='white')",
         "    ax.text(start + size / 2, 0, str(size), ha='center', va='center', color='white')",
         "ax.barh(0, a.cap - a.off, left=a.off, color='#dddddd')                  # free",
         "ax.set_xlim(0, a.cap); ax.set_yticks([]); ax.set_title('bump arena layout'); plt.show()"),
    md("## Takeaways",
       "",
       "- Stack = automatic LIFO; heap = you manage lifetime.",
       "- A bump allocator is O(1) and allocation-free at steady state — great for real-time loops.",
       "- Alignment costs a little padding but the hardware needs it.",
       "",
       "**Now build it** (alloc + reset, with OOM handling) in `homework.py`, then `pytest -q`."),
]


# --------------------------------------------------------------------------------------
# Day 18 — Syscalls
# --------------------------------------------------------------------------------------
DAY18 = [
    md("# Day 18 — Syscalls, Visualized",
       "",
       "`open().read()` bottoms out in kernel **system calls**. Let's use them directly, and see",
       "why buffer size changes how many times you cross the user/kernel boundary."),
    code("import os",
         "",
         "path = '/tmp/lp_day18_demo.txt'",
         "# Raw syscalls -- no Python file object:",
         "fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o644)",
         "os.write(fd, b'hello, kernel')",
         "os.close(fd)",
         "",
         "fd = os.open(path, os.O_RDONLY)",
         "print('read back:', os.read(fd, 100))",
         "print('size via lseek:', os.lseek(fd, 0, os.SEEK_END), 'bytes')",
         "os.close(fd)"),
    md("## Buffer size = number of syscalls",
       "",
       "Reading a file in tiny chunks means many `read` syscalls; a big buffer means few. Each",
       "crossing has a cost — this is why buffering exists."),
    code("data = bytes(10000)",
         "fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC); os.write(fd, data); os.close(fd)",
         "",
         "for chunk in (1, 64, 4096, 65536):",
         "    fd = os.open(path, os.O_RDONLY); calls = 0",
         "    while True:",
         "        calls += 1",
         "        if not os.read(fd, chunk): break",
         "    os.close(fd)",
         "    print(f'chunk={chunk:6d} bytes -> {calls:5d} read() syscalls')",
         "",
         "print('\\n(on Linux, run  strace -c python yourscript.py  to count real syscalls)')"),
    md("## Takeaways",
       "",
       "- A syscall is the user-space -> kernel doorway; file I/O, sockets, everything goes through it.",
       "- A file descriptor is just a small integer the kernel hands back.",
       "- Fewer, bigger operations beat many tiny ones — that's what buffering buys you.",
       "",
       "**Now build** low_level_write/read/copy + file_size in `homework.py`, then `pytest -q`."),
]


# --------------------------------------------------------------------------------------
# Day 20 — Profiling
# --------------------------------------------------------------------------------------
DAY20 = [
    md("# Day 20 — Profiling: Find the O(n^2), Visualized",
       "",
       "Correct but slow is still slow. The fix is almost always deleting an accidental nested",
       "loop. Measure it, then watch the linear version leave the quadratic one in the dust."),
    code("import timeit, random",
         "",
         "def naive_dup(items):",
         "    for i in range(len(items)):",
         "        for j in range(i + 1, len(items)):",
         "            if items[i] == items[j]: return True",
         "    return False",
         "",
         "def fast_dup(items):",
         "    seen = set()",
         "    for x in items:",
         "        if x in seen: return True",
         "        seen.add(x)",
         "    return False",
         "",
         "data = list(range(2000))            # all distinct -> worst case",
         "tn = timeit.timeit(lambda: naive_dup(data), number=3) / 3",
         "tf = timeit.timeit(lambda: fast_dup(data), number=3) / 3",
         "print(f'naive O(n^2): {tn*1000:8.2f} ms')",
         "print(f'fast  O(n):   {tf*1000:8.2f} ms   ({tn/tf:.0f}x faster)')"),
    md("## Runtime vs input size: the curves diverge"),
    code("import matplotlib.pyplot as plt",
         "",
         "sizes = [250, 500, 1000, 2000, 4000]",
         "naive_t, fast_t = [], []",
         "for n in sizes:",
         "    d = list(range(n))",
         "    naive_t.append(timeit.timeit(lambda: naive_dup(d), number=2) / 2)",
         "    fast_t.append(timeit.timeit(lambda: fast_dup(d), number=20) / 20)",
         "plt.figure(figsize=(7, 4))",
         "plt.plot(sizes, naive_t, marker='o', label='naive O(n^2)')",
         "plt.plot(sizes, fast_t, marker='s', label='fast O(n)')",
         "plt.xlabel('input size'); plt.ylabel('seconds'); plt.yscale('log')",
         "plt.title('Same answer, wildly different scaling'); plt.legend(); plt.grid(alpha=0.3); plt.show()"),
    md("## Takeaways",
       "",
       "- Profile before optimizing; the hot spot is rarely where you'd guess.",
       "- `x in set` is O(1) vs `x in list` O(n) — swapping the container often IS the fix.",
       "- Big-O predicts how badly it hurts as data grows.",
       "",
       "**Now optimize** has_duplicate & common_elements in `homework.py`, then `pytest -q`."),
]


# --------------------------------------------------------------------------------------
# Day 21 — Build Systems
# --------------------------------------------------------------------------------------
DAY21 = [
    md("# Day 21 — Build Systems, Visualized",
       "",
       "A build system topologically sorts a dependency graph (build prereqs first) and rebuilds",
       "only what a change affects. Here's the graph and the incremental logic."),
    code("DEPS = {",
         "    'app': ['main.o', 'util.o'],",
         "    'main.o': ['main.c', 'shared.h'],",
         "    'util.o': ['util.c', 'shared.h'],",
         "    'main.c': [], 'util.c': [], 'shared.h': [],",
         "}",
         "",
         "def build_order(deps):",
         "    color = {n: 0 for n in set(deps) | {p for ps in deps.values() for p in ps}}",
         "    order = []",
         "    def visit(n):",
         "        color[n] = 1",
         "        for p in sorted(deps.get(n, [])):",
         "            if color[p] == 0: visit(p)",
         "        color[n] = 2; order.append(n)",
         "    for n in sorted(color):",
         "        if color[n] == 0: visit(n)",
         "    return order",
         "",
         "print('build order:', build_order(DEPS))"),
    md("## Which change forces which rebuild?"),
    code("from collections import defaultdict",
         "",
         "def rebuild_set(deps, changed):",
         "    rev = defaultdict(set)",
         "    for t, ps in deps.items():",
         "        for p in ps: rev[p].add(t)",
         "    out, stack = set(), list(changed)",
         "    while stack:",
         "        for dep in rev.get(stack.pop(), ()):",
         "            if dep not in out: out.add(dep); stack.append(dep)",
         "    return out",
         "",
         "print(\"edit main.c  -> rebuild\", rebuild_set(DEPS, {'main.c'}))",
         "print(\"edit shared.h -> rebuild\", rebuild_set(DEPS, {'shared.h'}))",
         "print(\"edit nothing  -> rebuild\", rebuild_set(DEPS, set()))"),
    md("## Takeaways",
       "",
       "- Topological sort orders the build so prerequisites come first (a cycle is an error).",
       "- Incremental builds skip anything whose prerequisites didn't change — why `make` is fast.",
       "- Editing a shared header cascades to everything downstream.",
       "",
       "**Now build** build_order/needs_rebuild/rebuild_set in `homework.py`, then `pytest -q`.",
       "openpilot's scons does exactly this at scale."),
]


def main() -> None:
    targets = {
        "curriculum/week1_data_structures/day01_dynamic_arrays/lesson.ipynb": DAY01,
        "curriculum/week1_data_structures/day02_linked_lists/lesson.ipynb": DAY02,
        "curriculum/week1_data_structures/day04_hash_maps/lesson.ipynb": DAY04,
        "curriculum/week1_data_structures/day05_trees_bst/lesson.ipynb": DAY05,
        "curriculum/week1_data_structures/day06_heaps/lesson.ipynb": DAY06,
        "curriculum/week1_data_structures/day07_graphs/lesson.ipynb": DAY07,
        "curriculum/week2_operating_systems/day08_processes_scheduling/lesson.ipynb": DAY08,
        "curriculum/week2_operating_systems/day09_process_lifecycle/lesson.ipynb": DAY09,
        "curriculum/week2_operating_systems/day10_virtual_memory/lesson.ipynb": DAY10,
        "curriculum/week2_operating_systems/day11_threads_gil/lesson.ipynb": DAY11,
        "curriculum/week2_operating_systems/day12_synchronization/lesson.ipynb": DAY12,
        "curriculum/week2_operating_systems/day13_deadlock/lesson.ipynb": DAY13,
        "curriculum/week2_operating_systems/day14_ipc_pipes/lesson.ipynb": DAY14,
        "curriculum/week3_systems_programming/day15_memory_model/lesson.ipynb": DAY15,
        "curriculum/week3_systems_programming/day18_syscalls/lesson.ipynb": DAY18,
        "curriculum/week3_systems_programming/day20_profiling/lesson.ipynb": DAY20,
        "curriculum/week3_systems_programming/day21_build_systems/lesson.ipynb": DAY21,
        "curriculum/week4_pytorch_executorch/day22_tensors_autograd/lesson.ipynb": DAY22,
    }
    for rel, cells in targets.items():
        path = os.path.join(ROOT, rel)
        write_notebook(path, cells)
        print("wrote", rel, f"({len(cells)} cells)")


if __name__ == "__main__":
    main()
