#!/usr/bin/env python3
"""Regenerate the sample lesson notebooks from source.

Run from the repo root:  python tools/build_lessons.py   (or: make notebooks)

Notebooks are authored here as plain Python (via tools/nbbuild) so they diff cleanly and
are easy to review. Outputs are intentionally left empty — learners run the cells.
"""
from __future__ import annotations

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from nbbuild import code, md, write_notebook  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# --------------------------------------------------------------------------------------
# Day 01 — Dynamic Arrays
# --------------------------------------------------------------------------------------
DAY01 = [
    md("# Day 01 — Dynamic Arrays & Amortized Analysis",
       "",
       "A dynamic array feels infinite — you keep appending and it grows. But memory is",
       "fixed-size. The trick: when the block fills, allocate a **bigger** block and copy.",
       "Grow by *doubling* and appends stay cheap on average. Let's *see* it."),
    md("## `size` vs `capacity`",
       "",
       "- **size** (`len`): how many items you actually stored.",
       "- **capacity**: how many slots you've allocated. Always `>= size`.",
       "",
       "When `size == capacity`, the next append must resize."),
    code("class DemoArray:",
         "    \"\"\"A doubling array, instrumented so we can watch it grow.\"\"\"",
         "    def __init__(self):",
         "        self.cap = 1",
         "        self.n = 0",
         "        self.data = [None] * self.cap",
         "        self.copies = 0          # total element-copies done by resizes",
         "",
         "    def append(self, v):",
         "        cost = 1                 # writing the new element is 1 unit of work",
         "        if self.n == self.cap:   # full -> grow",
         "            self.cap *= 2",
         "            new = [None] * self.cap",
         "            for i in range(self.n):",
         "                new[i] = self.data[i]",
         "                self.copies += 1",
         "            cost += self.n       # ...plus the copies this append triggered",
         "            self.data = new",
         "        self.data[self.n] = v",
         "        self.n += 1",
         "        return cost"),
    code("a = DemoArray()",
         "history = []                     # (index, size, capacity, cost_of_this_append)",
         "for i in range(17):",
         "    c = a.append(i)",
         "    history.append((i, a.n, a.cap, c))",
         "",
         "print(f\"{'append#':>7} {'size':>5} {'capacity':>9} {'cost':>5}\")",
         "for idx, n, cap, cost in history:",
         "    print(f'{idx:>7} {n:>5} {cap:>9} {cost:>5}')"),
    md("## Capacity grows as a staircase of powers of two",
       "",
       "Notice capacity jumps 1 → 2 → 4 → 8 → 16 → 32, doubling only when it has to."),
    code("import matplotlib.pyplot as plt",
         "",
         "idx = [h[0] for h in history]",
         "size = [h[1] for h in history]",
         "cap = [h[2] for h in history]",
         "",
         "plt.figure(figsize=(7, 4))",
         "plt.step(idx, cap, where='post', label='capacity (allocated)')",
         "plt.plot(idx, size, marker='o', label='size (used)')",
         "plt.xlabel('append #'); plt.ylabel('slots')",
         "plt.title('Capacity doubles; size climbs by one')",
         "plt.legend(); plt.grid(alpha=0.3); plt.show()"),
    md("## Why it's *amortized O(1)*",
       "",
       "Most appends cost 1. A few (at each resize) cost a lot. But because resizes get",
       "**exponentially rarer**, the *average* cost per append stays flat and small."),
    code("costs = [h[3] for h in history]",
         "running_avg = [sum(costs[:k + 1]) / (k + 1) for k in range(len(costs))]",
         "",
         "fig, ax = plt.subplots(figsize=(7, 4))",
         "ax.bar(idx, costs, alpha=0.4, label='cost of each append')",
         "ax.plot(idx, running_avg, color='crimson', marker='o', label='running average cost')",
         "ax.set_xlabel('append #'); ax.set_ylabel('work units')",
         "ax.set_title('Spiky per-append cost, flat average → amortized O(1)')",
         "ax.legend(); ax.grid(alpha=0.3); plt.show()",
         "",
         "print('total copies for 17 appends:', a.copies)",
         "print('average cost per append:', round(running_avg[-1], 2))"),
    md("## Takeaways",
       "",
       "- Doubling makes total copy-work across *n* appends only ~*2n* → **O(1) amortized**.",
       "- Growing by a fixed `+k` instead would cost ~*n²/(2k)* → **O(n) per append**. Try it!",
       "",
       "**Now go implement it:** open `homework.py`, then run `pytest -q`. The grader's",
       "`test_amortized_constant_appends` fails loudly if you don't double."),
]


# --------------------------------------------------------------------------------------
# Day 08 — CPU Scheduling
# --------------------------------------------------------------------------------------
DAY08 = [
    md("# Day 08 — CPU Scheduling, Visualized",
       "",
       "One CPU, many ready processes. The OS must pick who runs next. Different **policies**",
       "make different trade-offs — let's render them as **Gantt charts** on one workload."),
    md("## The workload",
       "",
       "| Process | Arrival | Burst |",
       "|---|--:|--:|",
       "| P1 | 0 | 5 |",
       "| P2 | 1 | 3 |",
       "| P3 | 2 | 1 |",
       "",
       "A **process** is a running program with its own memory; the **burst** is how much CPU",
       "time it needs before it's done. (Threads share a process's memory — more on Day 11.)"),
    code("from collections import deque",
         "",
         "WORK = [('P1', 0, 5), ('P2', 1, 3), ('P3', 2, 1)]  # (pid, arrival, burst)",
         "",
         "def fcfs(work):",
         "    segs, t = [], 0",
         "    for pid, arr, burst in sorted(work, key=lambda p: (p[1], p[0])):",
         "        s = max(t, arr); segs.append((pid, s, s + burst)); t = s + burst",
         "    return segs",
         "",
         "def sjf(work):",
         "    rem, t, segs = list(work), 0, []",
         "    while rem:",
         "        ready = [p for p in rem if p[1] <= t]",
         "        if not ready:",
         "            t = min(p[1] for p in rem); continue",
         "        pid, arr, burst = min(ready, key=lambda p: (p[2], p[1], p[0]))",
         "        rem.remove((pid, arr, burst))",
         "        s = max(t, arr); segs.append((pid, s, s + burst)); t = s + burst",
         "    return segs",
         "",
         "def round_robin(work, q):",
         "    arr = sorted(work, key=lambda p: (p[1], p[0]))",
         "    rem = {p[0]: p[2] for p in work}; ready, segs, t, i = deque(), [], 0, 0",
         "    def board(upto):",
         "        nonlocal i",
         "        while i < len(arr) and arr[i][1] <= upto:",
         "            ready.append(arr[i][0]); i += 1",
         "    board(0)",
         "    while ready or i < len(arr):",
         "        if not ready:",
         "            t = arr[i][1]; board(t); continue",
         "        pid = ready.popleft(); run = min(q, rem[pid])",
         "        segs.append((pid, t, t + run)); t += run; rem[pid] -= run",
         "        board(t)",
         "        if rem[pid] > 0: ready.append(pid)",
         "    return segs",
         "",
         "for name, segs in [('FCFS', fcfs(WORK)), ('SJF', sjf(WORK)),",
         "                   ('RR q=2', round_robin(WORK, 2))]:",
         "    print(f'{name:8}', segs)"),
    md("## Gantt charts: who holds the CPU, when"),
    code("import matplotlib.pyplot as plt",
         "",
         "policies = {'FCFS': fcfs(WORK), 'SJF': sjf(WORK), 'Round-Robin (q=2)': round_robin(WORK, 2)}",
         "colors = {'P1': '#4C72B0', 'P2': '#DD8452', 'P3': '#55A868'}",
         "",
         "fig, axes = plt.subplots(len(policies), 1, figsize=(8, 5), sharex=True)",
         "for ax, (name, segs) in zip(axes, policies.items()):",
         "    for pid, s, e in segs:",
         "        ax.broken_barh([(s, e - s)], (0, 1), facecolors=colors[pid], edgecolor='white')",
         "        ax.text((s + e) / 2, 0.5, pid, va='center', ha='center', color='white', fontsize=9)",
         "    ax.set_title(name, loc='left', fontsize=10); ax.set_yticks([])",
         "axes[-1].set_xlabel('time (ticks)')",
         "plt.tight_layout(); plt.show()"),
    md("## How they compare on average waiting time",
       "",
       "**Waiting = turnaround − burst** (time spent ready but not running)."),
    code("def avg_wait(work, segs):",
         "    completion = {}",
         "    for pid, s, e in segs:",
         "        completion[pid] = max(completion.get(pid, 0), e)",
         "    waits = [completion[pid] - arr - burst for pid, arr, burst in work]",
         "    return sum(waits) / len(waits)",
         "",
         "names = list(policies)",
         "waits = [avg_wait(WORK, policies[n]) for n in names]",
         "plt.figure(figsize=(6, 3.5))",
         "plt.bar(names, waits, color=['#4C72B0', '#55A868', '#DD8452'])",
         "plt.ylabel('avg waiting time'); plt.title('Lower is snappier')",
         "for x, w in enumerate(waits): plt.text(x, w, f'{w:.2f}', ha='center', va='bottom')",
         "plt.show()"),
    md("## Takeaways",
       "",
       "- **FCFS**: simple, but a long job makes short jobs wait (convoy effect).",
       "- **SJF**: best average wait, but needs to know burst lengths and can starve long jobs.",
       "- **Round-Robin**: fair & responsive; the quantum tunes responsiveness vs. overhead.",
       "",
       "**Now go implement all three** in `homework.py` (with proper metrics) and run `pytest -q`."),
]


# --------------------------------------------------------------------------------------
# Day 22 — Tensors & Autograd
# --------------------------------------------------------------------------------------
DAY22 = [
    md("# Day 22 — Tensors & Autograd",
       "",
       "Autograd is how every neural net learns. It looks like magic; it's just calculus.",
       "Let's watch PyTorch differentiate, then train a line by gradient descent."),
    md("## Tensors that remember their history",
       "",
       "Set `requires_grad=True` and PyTorch records the operations you do, so it can replay",
       "them backwards to get gradients. For `y = x²`, calculus says `dy/dx = 2x`:"),
    code("import torch",
         "",
         "x = torch.tensor(3.0, requires_grad=True)",
         "y = x ** 2",
         "y.backward()          # compute dy/dx",
         "print('x =', x.item(), ' y = x^2 =', y.item(), ' dy/dx =', x.grad.item(), '(should be 2x = 6)')"),
    md("## Some noisy data from a line we'll pretend we don't know",
       "",
       "True relationship: `y = 3x + 2` plus noise. Can gradient descent recover 3 and 2?"),
    code("import matplotlib.pyplot as plt",
         "torch.manual_seed(0)",
         "",
         "x = torch.linspace(-1, 1, 60)",
         "y = 3.0 * x + 2.0 + 0.3 * torch.randn(60)",
         "plt.figure(figsize=(6, 4))",
         "plt.scatter(x, y, s=15, alpha=0.7)",
         "plt.title('data: y ≈ 3x + 2 + noise'); plt.xlabel('x'); plt.ylabel('y'); plt.show()"),
    md("## The training loop (the heart of all of PyTorch)",
       "",
       "**forward → loss → backward → update → zero_grad**, repeated. Watch the loss fall."),
    code("w = torch.zeros((), requires_grad=True)",
         "b = torch.zeros((), requires_grad=True)",
         "lr, losses = 0.1, []",
         "",
         "for epoch in range(200):",
         "    pred = w * x + b                 # forward",
         "    loss = ((pred - y) ** 2).mean()  # mean squared error",
         "    loss.backward()                  # autograd fills w.grad, b.grad",
         "    with torch.no_grad():            # update without recording it",
         "        w -= lr * w.grad",
         "        b -= lr * b.grad",
         "    w.grad.zero_(); b.grad.zero_()   # gradients accumulate — clear them!",
         "    losses.append(loss.item())",
         "",
         "print(f'learned w = {w.item():.3f} (true 3.0),  b = {b.item():.3f} (true 2.0)')"),
    code("fig, (axL, axR) = plt.subplots(1, 2, figsize=(11, 4))",
         "axL.plot(losses); axL.set_title('loss curve'); axL.set_xlabel('epoch')",
         "axL.set_ylabel('MSE'); axL.grid(alpha=0.3)",
         "",
         "axR.scatter(x, y, s=15, alpha=0.6, label='data')",
         "xs = torch.linspace(-1, 1, 2)",
         "axR.plot(xs, (w * xs + b).detach(), color='crimson', lw=2, label='learned line')",
         "axR.set_title('the fit'); axR.legend(); axR.grid(alpha=0.3)",
         "plt.tight_layout(); plt.show()"),
    md("## Takeaways",
       "",
       "- `requires_grad` + `.backward()` gives you exact gradients for free.",
       "- The five-line loop above is *every* PyTorch model — bigger models just have more",
       "  parameters and fancier `forward`s.",
       "- Forgetting `zero_grad()` is the classic beginner bug; the homework grader checks for it.",
       "",
       "**Now go implement** `numerical_gradient` (to prove autograd is right) and `fit_line`",
       "in `homework.py`, then run `pytest -q`."),
]


# --------------------------------------------------------------------------------------
# Day 02 — Linked Lists
# --------------------------------------------------------------------------------------
DAY02 = [
    md("# Day 02 — Linked Lists",
       "",
       "A dynamic array stores items shoulder-to-shoulder in one block, so inserting in the",
       "middle shoves everything after it over. A **linked list** threads items with pointers",
       "instead: each node points to its neighbours. Insert/delete at a known node is O(1)."),
    md("## A node is just a value plus two pointers",
       "",
       "`prev  ⟵  [ value ]  ⟶  next`. Chain them and you get a list you can walk both ways."),
    code("class Node:",
         "    def __init__(self, value):",
         "        self.value = value; self.prev = None; self.next = None",
         "",
         "def build(values):",
         "    head = None; tail = None",
         "    for v in values:",
         "        n = Node(v)",
         "        if tail: tail.next = n; n.prev = tail",
         "        else: head = n",
         "        tail = n",
         "    return head",
         "",
         "def forward(head):",
         "    out = []",
         "    while head: out.append(head.value); head = head.next",
         "    return out",
         "",
         "head = build([1, 2, 3, 4])",
         "print('forward:', forward(head))"),
    md("## Draw the chain"),
    code("import matplotlib.pyplot as plt",
         "",
         "def draw(head, title):",
         "    vals = forward(head)",
         "    fig, ax = plt.subplots(figsize=(1.6 * len(vals) + 1, 1.8))",
         "    for i, v in enumerate(vals):",
         "        ax.add_patch(plt.Rectangle((i * 2, 0), 1.2, 1, fill=True,",
         "                                   facecolor='#4C72B0', edgecolor='black'))",
         "        ax.text(i * 2 + 0.6, 0.5, str(v), ha='center', va='center', color='white')",
         "        if i < len(vals) - 1:",
         "            ax.annotate('', xy=(i * 2 + 2, 0.65), xytext=(i * 2 + 1.2, 0.65),",
         "                        arrowprops=dict(arrowstyle='->'))",
         "            ax.annotate('', xy=(i * 2 + 1.2, 0.35), xytext=(i * 2 + 2, 0.35),",
         "                        arrowprops=dict(arrowstyle='->', color='gray'))",
         "    ax.set_xlim(-0.5, 2 * len(vals)); ax.set_ylim(-0.3, 1.3)",
         "    ax.axis('off'); ax.set_title(title); plt.show()",
         "",
         "draw(head, 'blue = next,  gray = prev')"),
    md("## Insert 99 after the 2nd node: two pointers change, nothing shifts",
       "",
       "Compare that to a Python list, where `lst.insert(2, 99)` slides every later element."),
    code("def insert_after_index(head, index, value):",
         "    cur = head",
         "    for _ in range(index): cur = cur.next",
         "    n = Node(value)",
         "    n.prev = cur; n.next = cur.next",
         "    if cur.next: cur.next.prev = n",
         "    cur.next = n",
         "    return head        # only cur.next, n.prev/next, and one neighbour touched",
         "",
         "head = insert_after_index(head, 1, 99)",
         "print('after insert:', forward(head))",
         "draw(head, 'inserted 99 after index 1 — O(1) rewire')"),
    md("## Takeaways",
       "",
       "- Linked list: O(1) insert/delete at a known node, O(n) to *find* the i-th item.",
       "- Dynamic array: O(1) random access, O(n) middle insert.",
       "- *Doubly* linked (both `prev` and `next`) is what makes O(1) deletion and backward",
       "  walking possible.",
       "",
       "**Now build the real thing** in `homework.py` — the grader checks forward *and*",
       "backward traversal after every operation, so broken `prev` links get caught."),
]


# --------------------------------------------------------------------------------------
# Day 10 — Virtual Memory & Paging
# --------------------------------------------------------------------------------------
DAY10 = [
    md("# Day 10 — Virtual Memory & Page Replacement",
       "",
       "Memory is split into fixed-size **pages**; a **page table** maps virtual pages to",
       "physical frames. A miss is a **page fault** — load the page, maybe evict another.",
       "Which one to evict is the policy. Let's watch FIFO and LRU, and meet Belady's anomaly."),
    md("## 1. Address translation",
       "",
       "`vpn, offset = divmod(vaddr, page_size)`; the offset passes through, the page is remapped."),
    code("def translate(vaddr, page_size, page_table):",
         "    vpn, offset = divmod(vaddr, page_size)",
         "    if vpn not in page_table: raise KeyError(f'page fault: vpn {vpn}')",
         "    return page_table[vpn] * page_size + offset",
         "",
         "# page 1 -> frame 2, page size 256; vaddr 356 = page 1, offset 100",
         "print('vaddr 356 ->', translate(356, 256, {0: 5, 1: 2}), '(= frame 2 * 256 + 100)')"),
    md("## 2. FIFO vs LRU on the classic reference string"),
    code("from collections import OrderedDict, deque",
         "",
         "BELADY = [1, 2, 3, 4, 1, 2, 5, 1, 2, 3, 4, 5]",
         "",
         "def fifo(refs, k):",
         "    frames, order, faults = set(), deque(), 0",
         "    for p in refs:",
         "        if p not in frames:",
         "            faults += 1",
         "            if len(frames) >= k: frames.discard(order.popleft())",
         "            frames.add(p); order.append(p)",
         "    return faults",
         "",
         "def lru(refs, k):",
         "    frames, faults = OrderedDict(), 0",
         "    for p in refs:",
         "        if p in frames: frames.move_to_end(p)",
         "        else:",
         "            faults += 1",
         "            if len(frames) >= k: frames.popitem(last=False)",
         "            frames[p] = None",
         "    return faults",
         "",
         "print('FIFO 3 frames:', fifo(BELADY, 3), 'faults')",
         "print('FIFO 4 frames:', fifo(BELADY, 4), 'faults  <-- MORE frames, MORE faults!')",
         "print('LRU  3 frames:', lru(BELADY, 3), 'faults')"),
    md("## 3. Belady's anomaly, plotted",
       "",
       "For a well-behaved policy, more frames ⇒ fewer (or equal) faults. FIFO breaks that."),
    code("import matplotlib.pyplot as plt",
         "",
         "frames = list(range(1, 7))",
         "fifo_faults = [fifo(BELADY, k) for k in frames]",
         "lru_faults = [lru(BELADY, k) for k in frames]",
         "",
         "plt.figure(figsize=(7, 4))",
         "plt.plot(frames, fifo_faults, marker='o', label='FIFO')",
         "plt.plot(frames, lru_faults, marker='s', label='LRU')",
         "plt.axvspan(2.5, 4.5, color='crimson', alpha=0.08)",
         "plt.text(3.5, max(fifo_faults), 'FIFO goes UP here\\n(Belady anomaly)',",
         "         ha='center', va='top', color='crimson', fontsize=9)",
         "plt.xlabel('number of frames'); plt.ylabel('page faults')",
         "plt.title('More memory should mean fewer faults — FIFO disagrees')",
         "plt.legend(); plt.grid(alpha=0.3); plt.show()"),
    md("## Takeaways",
       "",
       "- Translation splits an address into (page, offset); only the page is remapped.",
       "- FIFO evicts by *load order* and can suffer **Belady's anomaly** — more frames, more",
       "  faults. LRU evicts by *use order* and never does (it's a 'stack algorithm').",
       "",
       "**Now implement** `translate`, `fifo`, and `lru` in `homework.py` (returning per-step",
       "history), then run `pytest -q`."),
]


def main() -> None:
    targets = {
        "curriculum/week1_data_structures/day01_dynamic_arrays/lesson.ipynb": DAY01,
        "curriculum/week1_data_structures/day02_linked_lists/lesson.ipynb": DAY02,
        "curriculum/week2_operating_systems/day08_processes_scheduling/lesson.ipynb": DAY08,
        "curriculum/week2_operating_systems/day10_virtual_memory/lesson.ipynb": DAY10,
        "curriculum/week4_pytorch_executorch/day22_tensors_autograd/lesson.ipynb": DAY22,
    }
    for rel, cells in targets.items():
        path = os.path.join(ROOT, rel)
        write_notebook(path, cells)
        print("wrote", rel, f"({len(cells)} cells)")


if __name__ == "__main__":
    main()
